### ISSUE TITLE
install failed in the vlan mode of underlay

### ISSUE THREAD

**Issue by renyunkang** [kubeovn/kube-ovn#1367]
# Expected Behavior
installation successful
# Actual Behavior
installation failed
# Steps to Reproduce the Problem
1. install using a script in a single NIC environment.

- Kubernetes version:
```
root@node1:~/kube-ovn# kubectl  version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691",
GitTreeState:"clean", BuildDate:"2021-09-15T21:10:45Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691",
GitTreeState:"clean", BuildDate:"2021-09-15T21:04:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```

Three-node + single-NIC environment. When installing in the vlan mode of underlay, configure the network segment and gateway with the podCIDR consistent with the host. The fourth step installation failed.
```
REGISTRY="kubeovn"
VERSION="v1.9.0"
IMAGE_PULL_POLICY="IfNotPresent"
POD_CIDR="192.168.2.0/24"                # Do NOT overlap with NODE/SVC/JOIN CIDR
POD_GATEWAY="192.168.2.1"
SVC_CIDR="10.96.0.0/12"                # Do NOT overlap with NODE/POD/JOIN CIDR
JOIN_CIDR="100.64.0.0/16"              # Do NOT overlap with NODE/POD/SVC CIDR
PINGER_EXTERNAL_ADDRESS="114.114.114.114"  # Pinger check external ip probe
PINGER_EXTERNAL_DOMAIN="alauda.cn"         # Pinger check external domain probe
SVC_YAML_IPFAMILYPOLICY=""
...

EXCLUDE_IPS="192.168.2.100..192.168.2.110"                         # EXCLUDE_IPS for default subnet
LABEL="node-role.kubernetes.io/master" # The node label to deploy OVN DB
NETWORK_TYPE="vlan"                  # geneve or vlan
TUNNEL_TYPE="geneve"                   # geneve, vxlan or stt. ATTENTION: some networkpolicy cannot take effect when using vxlan and stt need custom compile ovs kernel module
POD_NIC_TYPE="veth-pair"               # veth-pair or internal-port

# VLAN Config only take effect when NETWORK_TYPE is vlan
PROVIDER_NAME="provider"
VLAN_INTERFACE_NAME="eth0"
VLAN_NAME="ovn-vlan"
VLAN_ID="0"
```
err.log
```
... ...
-------------------------------

[Step 4/6] Delete pod that not in host network mode
pod "coredns-5495dd7c88-bdxh4" deleted
pod "coredns-5495dd7c88-xpngt" deleted
daemon set "kube-ovn-pinger" successfully rolled out
Waiting for deployment "coredns" rollout to finish: 0 of 2 updated replicas are available...
error: timed out waiting for the condition
```
Node network information: 
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 52:54:99:fd:49:5f brd ff:ff:ff:ff:ff:ff
    inet 192.168.2.101/24 brd 192.168.2.255 scope global dynamic eth0
       valid_lft 86359sec preferred_lft 86359sec
    inet6 fe80::5054:99ff:fefd:495f/64 scope link
       valid_lft forever preferred_lft forever
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:70:64:55:61 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
4: nodelocaldns: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN group default
    link/ether 36:89:e3:0b:7a:5f brd ff:ff:ff:ff:ff:ff
    inet 169.254.25.10/32 brd 169.254.25.10 scope global nodelocaldns
       valid_lft forever preferred_lft forever
```
The error information reported by `pinger` and `coredns` is consistent: the corresponding kubernetes service cannot be connected.
```
root@node1:~/kube-ovn# kubectl  get svc
NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
kubernetes   ClusterIP   10.233.0.1   <none>        443/TCP   57m


root@node1:~/kube-ovn# kubectl  logs kube-ovn-pinger-c7fkl -n kube-system
I0309 22:57:03.252315   52240 pinger.go:19]
-------------------------------------------------------------------------------
Kube-OVN:
  Version:       v1.9.0
  Build:         2022-01-12_05:50:51
  Commit:        git-ee7b17c
  Go Version:    go1.17.5
  Arch:          amd64
-------------------------------------------------------------------------------
E0309 22:57:18.254795   52240 config.go:143] failed to get self pod kube-system/kube-ovn-pinger-c7fkl: Get "https://10.233.0.1:443/api/v1/namespaces/kube-system/pods/kube-ovn-pinger-c7fkl?timeout=15s": dial tcp 10.233.0.1:443: i/o timeout
F0309 22:57:18.255058   52240 pinger.go:24] parse config failed Get "https://10.233.0.1:443/api/v1/namespaces/kube-system/pods/kube-ovn-pinger-c7fkl?timeout=15s": dial tcp 10.233.0.1:443: i/o timeout
goroutine 1 [running]:
k8s.io/klog/v2.stacks(0x1)
        /home/runner/go/pkg/mod/k8s.io/klog/v2@v2.30.0/klog.go:1038 +0x8a
k8s.io/klog/v2.(*loggingT).output(0x56171362d680, 0x3, 0x0, 0xc0006bd960, 0x0, {0x561712b2b57c, 0x1}, 0xc0000a5df0, 0x0)
        /home/runner/go/pkg/mod/k8s.io/klog/v2@v2.30.0/klog.go:987 +0x5fd
k8s.io/klog/v2.(*loggingT).printf(0x5, 0x5, 0x0, {0x0, 0x0}, {0x56171125d07b, 0x16}, {0xc0000a5df0, 0x1, 0x1})
        /home/runner/go/pkg/mod/k8s.io/klog/v2@v2.30.0/klog.go:753 +0x1c5
k8s.io/klog/v2.Fatalf(...)
        /home/runner/go/pkg/mod/k8s.io/klog/v2@v2.30.0/klog.go:1532
github.com/kubeovn/kube-ovn/cmd/pinger.CmdMain()
        /home/runner/work/kube-ovn/kube-ovn/cmd/pinger/pinger.go:24 +0x259
main.main()
        /home/runner/work/kube-ovn/kube-ovn/cmd/cmdmain.go:39 +0xf5

goroutine 20 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0xc0000bec00)
        /home/runner/go/pkg/mod/k8s.io/klog/v2@v2.30.0/klog.go:1181 +0x6a
created by k8s.io/klog/v2.init.0
        /home/runner/go/pkg/mod/k8s.io/klog/v2@v2.30.0/klog.go:420 +0xfb

goroutine 29 [sleep]:
time.Sleep(0x6fc23ac00)
        /opt/hostedtoolcache/go/1.17.5/x64/src/runtime/time.go:193 +0x12e
sigs.k8s.io/controller-runtime/pkg/log.init.0.func1()
        /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/log/log.go:63 +0x38
created by sigs.k8s.io/controller-runtime/pkg/log.init.0
        /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/log/log.go:62 +0x25

goroutine 116 [select]:
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000118240, {0x561712617e40, 0xc0002be000}, 0x1, 0x0)
        /home/runner/go/pkg/mod/k8s.io/apimachinery@v0.23.1/pkg/util/wait/wait.go:167 +0x13b
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00037f668, 0x12a05f200, 0x0, 0x10, 0x56170fd0f1c5)
        /home/runner/go/pkg/mod/k8s.io/apimachinery@v0.23.1/pkg/util/wait/wait.go:133 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(0xc000118240, 0x0, 0xc000118240)
        /home/runner/go/pkg/mod/k8s.io/apimachinery@v0.23.1/pkg/util/wait/wait.go:90 +0x25
created by github.com/kubeovn/kube-ovn/pkg/util.InitKlogMetrics
        /home/runner/work/kube-ovn/kube-ovn/pkg/util/klog_metrics.go:24 +0x5a
```
node + pod information:
```
root@node1:~/kube-ovn# kubectl get node -o wide
NAME    STATUS   ROLES                         AGE   VERSION   INTERNAL-IP     EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION     CONTAINER-RUNTIME
node1   Ready    control-plane,master,worker   56m   v1.21.5   192.168.2.101   <none>        Ubuntu 20.04.3 LTS   5.4.0-91-generic   docker://20.10.12
node2   Ready    worker                        55m   v1.21.5   192.168.2.102   <none>        Ubuntu 20.04.3 LTS   5.4.0-91-generic   docker://20.10.12
node3   Ready    worker                        55m   v1.21.5   192.168.2.103   <none>        Ubuntu 20.04.3 LTS   5.4.0-91-generic   docker://20.10.12


root@node1:~/kube-ovn# kubectl  get pod -A -o wide
NAMESPACE     NAME                                   READY   STATUS             RESTARTS   AGE   IP              NODE    NOMINATED NODE   READINESS GATES
kube-system   coredns-5495dd7c88-5ptdj               0/1     Running            0          18m   192.168.2.2     node3   <none>           <none>
kube-system   coredns-5495dd7c88-vszhk               0/1     Running            0          18m   192.168.2.111   node3   <none>           <none>
kube-system   kube-apiserver-node1                   1/1     Running            0          55m   192.168.2.101   node1   <none>           <none>
kube-system   kube-controller-manager-node1          1/1     Running            0          55m   192.168.2.101   node1   <none>           <none>
kube-system   kube-ovn-cni-8vgx8                     1/1     Running            0          18m   192.168.2.101   node1   <none>           <none>
kube-system   kube-ovn-cni-kg74l                     1/1     Running            0          18m   192.168.2.103   node3   <none>           <none>
kube-system   kube-ovn-cni-nbb7j                     1/1     Running            0          18m   192.168.2.102   node2   <none>           <none>
kube-system   kube-ovn-controller-56bfc9895c-rjngq   1/1     Running            0          18m   192.168.2.103   node3   <none>           <none>
kube-system   kube-ovn-monitor-74df8fb5b6-bwbjb      1/1     Running            0          18m   192.168.2.101   node1   <none>           <none>
kube-system   kube-ovn-pinger-bhglm                  0/1     Error              8          18m   192.168.2.112   node2   <none>           <none>
kube-system   kube-ovn-pinger-c7fkl                  0/1     Error              8          18m   192.168.2.4     node1   <none>           <none>
kube-system   kube-ovn-pinger-lxfxr                  0/1     CrashLoopBackOff   8          18m   192.168.2.3     node3   <none>           <none>
kube-system   kube-proxy-ggkwq                       1/1     Running            0          55m   192.168.2.101   node1   <none>           <none>
kube-system   kube-proxy-gxtzn                       1/1     Running            0          54m   192.168.2.102   node2   <none>           <none>
kube-system   kube-proxy-pxlwk                       1/1     Running            0          54m   192.168.2.103   node3   <none>           <none>
kube-system   kube-scheduler-node1                   1/1     Running            0          55m   192.168.2.101   node1   <none>           <none>
kube-system   nodelocaldns-79jtm                     1/1     Running            0          55m   192.168.2.101   node1   <none>           <none>
kube-system   nodelocaldns-wbjwx                     1/1     Running            0          54m   192.168.2.103   node3   <none>           <none>
kube-system   nodelocaldns-zz4gv                     1/1     Running            0          54m   192.168.2.102   node2   <none>           <none>
kube-system   ovn-central-584db65c95-llzls           1/1     Running            0          18m   192.168.2.101   node1   <none>           <none>
kube-system   ovs-ovn-95zkr                          1/1     Running            0          18m   192.168.2.101   node1   <none>           <none>
kube-system   ovs-ovn-fh9ng                          1/1     Running            0          18m   192.168.2.103   node3   <none>           <none>
kube-system   ovs-ovn-sj4cq                          1/1     Running            0          18m   192.168.2.102   node2   <none>           <none>
```
Is my configuration wrong?
If it is a node with multiple network cards, is it necessary to have a built-in Layer 2 network environment for the container network to be installed?

**Comment by zhangzujian** [comment]
IP addresses assigned to eth0, such as 192.168.2.101/24, will be moved to an OVS bridge named `br-provider`. Pods on the node will be connected to the same bridge. So you can check whether a node can communicate with Pods on it to verify the bridge is set up correctly.

Then you should check the [environment requirements](https://github.com/kubeovn/kube-ovn/blob/master/docs/vlan.md#environment-requirements). Considering your issue, there is a high possibility that the fifth point is not satisfied.
