### ISSUE TITLE
Underlay/Overlay 混合网络的集群，机器重启后kube-ovn启动异常

### ISSUE THREAD

**Issue by lv88** [kubeovn/kube-ovn#1964]
# Expected Behavior
Underlay/Overlay 混合网络的集群，出现机器重启的情形，集群服务会恢复
# Actual Behavior
重启后，默认子网虚拟网卡ovn0没能激活，原网卡的ip和路由转移到自建子网创建的虚拟网卡（网桥），但是已经无法和集群内的其他机器通信（ping不通了）
# Steps to Reproduce the Problem

1. k8s集群(120.0.0.105\142\143),其中，105是master，142和143都是worker节点。
2. 按官网安装说明部署为 Overlay 类型网络。
3. 安装官网“通过 CRD 动态创建 Underlay 网络”说明，手动创建ProviderNetwork(设置name为net1)，Vlan和Subnet。各节点都多了名为br-net1的虚拟网卡（原网卡的ip转移到该网桥）。通过ifconfig命令查看各节点，都有ovn0和br-net1。
4. 重启节点（比如142后），发现br-net1还有，但是ovn0没有了。查看/var/log/kube-ovn/kube-ovn-cni.log：
  ```
Log file created at: 2022/10/14 09:48:10
Running on machine: node4143
Binary: Built with gc go1.18.5 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
Log file created at: 2022/10/14 09:50:52
Running on machine: node4143
Binary: Built with gc go1.18.5 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I1014 09:50:52.186355   20912 cniserver.go:34] 
-------------------------------------------------------------------------------
Kube-OVN: 
  Version:       v1.10.6
  Build:         2022-08-30_08:58:37
  Commit:        git-1510905
  Go Version:    go1.18.5
  Arch:          amd64
-------------------------------------------------------------------------------
I1014 09:50:52.299066   20912 config.go:136] node name not specified in command line parameters, fall back to the environment variable
I1014 09:50:52.299152   20912 config.go:297] no --kubeconfig, use in-cluster kubernetes config
E1014 09:50:55.202212   20912 config.go:162] Failed to find node info, err: Get "https://10.244.64.1:443/api/v1/nodes/11.0.4.143": dial tcp 10.244.64.1:443: connect: no route to host
F1014 09:50:55.202313   20912 cniserver.go:46] failed to initialize config: Get "https://10.244.64.1:443/api/v1/nodes/11.0.4.143": dial tcp 10.244.64.1:443: connect: no route to host
goroutine 1 [running]:
k8s.io/klog/v2/internal/dbg.Stacks(0x1)
	/home/runner/go/pkg/mod/k8s.io/klog/v2@v2.70.1/internal/dbg/dbg.go:35 +0x8a
k8s.io/klog/v2.(*loggingT).output(0x560b2cb58e20, 0x3, 0x0, 0xc0002140e0, 0x1, {0x560b2c052b82?, 0x1?}, 0x560b2cb75ec0?, 0x0)
	/home/runner/go/pkg/mod/k8s.io/klog/v2@v2.70.1/klog.go:940 +0x6af
k8s.io/klog/v2.(*loggingT).printfDepth(0x560b2cb58e20, 0x5?, 0x0, {0x0, 0x0}, 0x0?, {0x560b2ad3ab00, 0x1f}, {0xc0004f5510, 0x1, ...})
	/home/runner/go/pkg/mod/k8s.io/klog/v2@v2.70.1/klog.go:737 +0x1f3
k8s.io/klog/v2.(*loggingT).printf(...)
	/home/runner/go/pkg/mod/k8s.io/klog/v2@v2.70.1/klog.go:719
k8s.io/klog/v2.Fatalf(...)
	/home/runner/go/pkg/mod/k8s.io/klog/v2@v2.70.1/klog.go:1618
github.com/kubeovn/kube-ovn/cmd/daemon.CmdMain()
	/home/runner/work/kube-ovn/kube-ovn/cmd/daemon/cniserver.go:46 +0x368
main.main()
	/home/runner/work/kube-ovn/kube-ovn/cmd/cmdmain.go:38 +0xac

goroutine 4 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x0?)
	/home/runner/go/pkg/mod/github.com/golang/glog@v1.0.0/glog.go:882 +0x6a
created by github.com/golang/glog.init.0
	/home/runner/go/pkg/mod/github.com/golang/glog@v1.0.0/glog.go:410 +0x1bf

goroutine 54 [select]:
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x560b29576ff6?, {0x560b2bae6e08, 0xc0001910b0}, 0x1, 0x0)
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/wait/wait.go:167 +0x135
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x0?, 0x12a05f200, 0x0, 0x0?, 0x560b2957dee5?)
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/wait/wait.go:133 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(0xc000580840?, 0xc00021d6c0?, 0xc000580840?)
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/util/wait/wait.go:90 +0x25
created by github.com/kubeovn/kube-ovn/pkg/util.InitKlogMetrics
	/home/runner/work/kube-ovn/kube-ovn/pkg/util/klog_metrics.go:24 +0x25

goroutine 55 [select]:
k8s.io/klog/v2.(*flushDaemon).run.func1()
	/home/runner/go/pkg/mod/k8s.io/klog/v2@v2.70.1/klog.go:1136 +0x11e
created by k8s.io/klog/v2.(*flushDaemon).run
	/home/runner/go/pkg/mod/k8s.io/klog/v2@v2.70.1/klog.go:1132 +0x178
  ```

# Additional Info

- Kubernetes version:
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:25:06Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
```

- kube-ovn version:
  
```
Kube-OVN: 
Version:       v1.10.6
Build:         2022-08-30_08:58:37
Commit:        git-1510905
Go Version:    go1.18.5
Arch:          amd64
```

**Comment by lv88** [comment]
补充安装配置：
POD_CIDR="10.16.0.0/16"   
POD_GATEWAY="10.16.0.1"
SVC_CIDR="10.244.64.0/18" 
JOIN_CIDR="100.64.0.0/16"

**Comment by zhangzujian** [comment]
检查一下节点是否禁用了 IPv6：

```sh
cat /proc/sys/net/ipv6/conf/all/disable_ipv6
```

**Comment by oilbeater** [comment]
是否 overlay 和 underlay 用的是同一个网卡？

**Comment by lv88** [comment]
> 

值为0，没有禁用IPv6

**Comment by lv88** [comment]
集群节点只有一个网卡，所以，overlay和underlay用的是同一个网卡。

**Comment by lv88** [comment]
单网卡混合部署的问题，存在于目前已发布的各个版本（v1.8.12、v1.9.10、v1.10.6），目前开发阶段的v1.11.0也有这样的问题。

**Comment by zhangzujian** [comment]
环境： VMWare 虚拟机 + CentOS 7.9
问题：节点重启后，ens33 的 IP及路由能够正常转移到 br-net1，但节点无法通过 br-net1 与外部通信。手动将 ens33 从 br-net1 中删除并恢复节点网络后，kube-ovn-cni 会自动将 ens33 重新加入 br-net1，此过程不会导致网络故障。仅 worker 节点会出现此问题（必现），master 节点正常。
已排查：br-net1 的流表、OVS trace、NetworkManager、系统日志等。
