### ISSUE TITLE
statefulset pod 重启后IP发生改变

### ISSUE THREAD

**Issue by wolgod** [kubeovn/kube-ovn#3222]
# Expected Behavior
  pod ip改变
# Actual Behavior
pod ip不变
# Steps to Reproduce the Problem

 
kubeovn 1.8.0 中使用statefulset 固定ip地址,pod正常重启 ip不会改变
现在遇到ceph故障,导致pod的pvc无法卸载,pod处于Terminating 状态一段时间,后来通过重启宿主机解决了无法卸载的问题,但是
发现重启节点后pod恢复Running后pod的ip 发送了

**Comment by oilbeater** [comment]
有没有那段时间的 kube-ovn-controller 日志可以过滤一下看看这个 ip 的分配和释放过程，以及需要你使用的 kube-ovn 的版本

**Comment by oilbeater** [comment]
@wolgod 1.8 的版本已经不再维护了，建议升级到新的版本，ipam 初始化的逻辑做过比较大的调整

**Comment by wolgod** [comment]
`
goroutine 2279 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x55e0c4685c80, 0x55e0c490d540)
        /home/runner/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/runtime/runtime.go:74 +0x95
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /home/runner/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/runtime/runtime.go:48 +0x87
panic(0x55e0c4685c80, 0x55e0c490d540)
        /opt/hostedtoolcache/go/1.16.7/x64/src/runtime/panic.go:965 +0x1b9
github.com/kubeovn/kube-ovn/pkg/controller.(*Controller).handleUpdatePod(0xc000a9d200, 0xc0019fa600, 0x33, 0x0, 0x0)
        /home/runner/work/kube-ovn/kube-ovn/pkg/controller/pod.go:748 +0x4e5
github.com/kubeovn/kube-ovn/pkg/controller.(*Controller).processNextUpdatePodWorkItem.func1(0xc000a9d200, 0x55e0c45f1e40, 0xc00a1a7570, 0x0, 0x0)
        /home/runner/work/kube-ovn/kube-ovn/pkg/controller/pod.go:335 +0xe9
github.com/kubeovn/kube-ovn/pkg/controller.(*Controller).processNextUpdatePodWorkItem(0xc000a9d200, 0x203001)
        /home/runner/work/kube-ovn/kube-ovn/pkg/controller/pod.go:341 +0x50
github.com/kubeovn/kube-ovn/pkg/controller.(*Controller).runUpdatePodWorker(...)
        /home/runner/work/kube-ovn/kube-ovn/pkg/controller/pod.go:241
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0046e7740)
        /home/runner/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:155 +0x62
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0046e7740, 0x55e0c492b828, 0xc002614450, 0x1, 0xc0001142a0)
        /home/runner/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:156 +0x9b
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0046e7740, 0x3b9aca00, 0x0, 0x1, 0xc0001142a0)
        /home/runner/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:133 +0x9a
k8s.io/apimachinery/pkg/util/wait.Until(0xc0046e7740, 0x3b9aca00, 0xc0001142a0)
        /home/runner/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:90 +0x4f
created by github.com/kubeovn/kube-ovn/pkg/controller.(*Controller).startWorkers
        /home/runner/work/kube-ovn/kube-ovn/pkg/controller/controller.go:530 +0x1065
panic: assignment to entry in nil map [recovered]
        panic: assignment to entry in nil map

goroutine 2279 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /home/runner/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/runtime/runtime.go:55 +0x10a
panic(0x55e0c4685c80, 0x55e0c490d540)
        /opt/hostedtoolcache/go/1.16.7/x64/src/runtime/panic.go:965 +0x1b9
github.com/kubeovn/kube-ovn/pkg/controller.(*Controller).handleUpdatePod(0xc000a9d200, 0xc0019fa600, 0x33, 0x0, 0x0)
        /home/runner/work/kube-ovn/kube-ovn/pkg/controller/pod.go:748 +0x4e5
github.com/kubeovn/kube-ovn/pkg/controller.(*Controller).processNextUpdatePodWorkItem.func1(0xc000a9d200, 0x55e0c45f1e40, 0xc00a1a7570, 0x0, 0x0)
        /home/runner/work/kube-ovn/kube-ovn/pkg/controller/pod.go:335 +0xe9
github.com/kubeovn/kube-ovn/pkg/controller.(*Controller).processNextUpdatePodWorkItem(0xc000a9d200, 0x203001)
        /home/runner/work/kube-ovn/kube-ovn/pkg/controller/pod.go:341 +0x50
github.com/kubeovn/kube-ovn/pkg/controller.(*Controller).runUpdatePodWorker(...)
        /home/runner/work/kube-ovn/kube-ovn/pkg/controller/pod.go:241
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0046e7740)
        /home/runner/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:155 +0x62
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0046e7740, 0x55e0c492b828, 0xc002614450, 0x1, 0xc0001142a0)
        /home/runner/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:156 +0x9b
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0046e7740, 0x3b9aca00, 0x0, 0x1, 0xc0001142a0)
        /home/runner/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:133 +0x9a
k8s.io/apimachinery/pkg/util/wait.Until(0xc0046e7740, 0x3b9aca00, 0xc0001142a0)
        /home/runner/go/pkg/mod/k8s.io/apimachinery@v0.20.4/pkg/util/wait/wait.go:90 +0x4f
created by github.com/kubeovn/kube-ovn/pkg/controller.(*Controller).startWorkers
        /home/runner/work/kube-ovn/kube-ovn/pkg/controller/controller.go:530 +0x1065
`
异常日志如上

**Comment by wolgod** [comment]
> @wolgod 1.8 的版本已经不再维护了，建议升级到新的版本，ipam 初始化的逻辑做过比较大的调整

我想问下，最新的版本的statefulset 固定pod的ip的逻辑会持久化pod的ip，会像1.8.0版本这样还是保存在内存里，如果ovn-controller主节点切换的话，会丢失部分statefulset的pod ip
